### ISSUE TITLE
empty folder causes error 

### ISSUE THREAD

**Issue by andreawyss** [wilsonlewis/require-context#5]
If an empty folder exists inside the recursed structure it causes this error:

node_modules/node-dir/lib/paths.js:92
                results.files = results.files.concat(res.files);

TypeError: Cannot read property 'files' of undefined
    at subloop (/git/mobile.reactnative.templateapp/node_modules/node-dir/lib/paths.js:92:57)
    at /git/mobile.reactnative.templateapp/node_modules/node-dir/lib/paths.js:107:13

Error reproduced on MAC with node 6 and node 8

**Comment by busegenc** [comment]
I had the same error. Removing empty folders fixes the problem.

**Comment by tusharkotlapure** [comment]
Is there any permanent fix for this issue?

**Comment by sebinsua** [comment]
@tusharkotlapure Don't use this package. Use [`node-require-context`](https://github.com/itlangzi/node-require-context).

**Comment by mgd216** [comment]
I had the same issue, did not realize another dev had removed files in a directory and it was empty.  Took a while to use the debugger to find out the dependency node-dir throws an error on an empty folder.  On node-dir/lib/paths.js line 86 would add a check: if (res &&  type ==='combine') .
